package universite.EtudiantPackage;


/**
* universite/EtudiantPackage/MatieresHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 3 mai 2019 10 h 05 CEST
*/

public final class MatieresHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public MatieresHolder ()
  {
  }

  public MatieresHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = universite.EtudiantPackage.MatieresHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    universite.EtudiantPackage.MatieresHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return universite.EtudiantPackage.MatieresHelper.type ();
  }

}
