package universite.EtudiantPackage;


/**
* universite/EtudiantPackage/Resultat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 3 mai 2019 10 h 05 CEST
*/

public final class Resultat implements org.omg.CORBA.portable.IDLEntity
{
  public String matiere = null;
  public float note = (float)0;

  public Resultat ()
  {
  } // ctor

  public Resultat (String _matiere, float _note)
  {
    matiere = _matiere;
    note = _note;
  } // ctor

} // class Resultat
