package helloApp;


/**
* helloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from helloApp.idl
* vendredi 16 mars 2018 13 h 49 CET
*/

public interface HelloOperations 
{
  String sayHello();
} // interface HelloOperations
