package callbacks;

/**
* callbacks/CallbackClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callbacks.idl
* vendredi 3 mai 2019 11 h 30 CEST
*/

public final class CallbackClientHolder implements org.omg.CORBA.portable.Streamable
{
  public callbacks.CallbackClient value = null;

  public CallbackClientHolder ()
  {
  }

  public CallbackClientHolder (callbacks.CallbackClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = callbacks.CallbackClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    callbacks.CallbackClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return callbacks.CallbackClientHelper.type ();
  }

}
