package callbacks;


/**
* callbacks/CallbackClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callbacks.idl
* vendredi 3 mai 2019 11 h 30 CEST
*/

public interface CallbackClient extends CallbackClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CallbackClient
