package universite;


/**
* universite/EtudiantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 3 mai 2019 10 h 05 CEST
*/

public abstract class EtudiantPOA extends org.omg.PortableServer.Servant
 implements universite.EtudiantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ajouterNoteDans", new java.lang.Integer (0));
    _methods.put ("listeMatieres", new java.lang.Integer (1));
    _methods.put ("listeNotes", new java.lang.Integer (2));
    _methods.put ("moyenne", new java.lang.Integer (3));
    _methods.put ("listeResultats", new java.lang.Integer (4));
    _methods.put ("_get_numCarte", new java.lang.Integer (5));
    _methods.put ("_get_nom", new java.lang.Integer (6));
    _methods.put ("_set_nom", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // universite/Etudiant/ajouterNoteDans
       {
         float note = in.read_float ();
         String matiere = in.read_string ();
         this.ajouterNoteDans (note, matiere);
         out = $rh.createReply();
         break;
       }

       case 1:  // universite/Etudiant/listeMatieres
       {
         String $result[] = null;
         $result = this.listeMatieres ();
         out = $rh.createReply();
         universite.EtudiantPackage.MatieresHelper.write (out, $result);
         break;
       }

       case 2:  // universite/Etudiant/listeNotes
       {
         float $result[] = null;
         $result = this.listeNotes ();
         out = $rh.createReply();
         universite.EtudiantPackage.NotesHelper.write (out, $result);
         break;
       }

       case 3:  // universite/Etudiant/moyenne
       {
         float $result = (float)0;
         $result = this.moyenne ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // universite/Etudiant/listeResultats
       {
         universite.EtudiantPackage.Resultat $result[] = null;
         $result = this.listeResultats ();
         out = $rh.createReply();
         universite.EtudiantPackage.ResultatsHelper.write (out, $result);
         break;
       }

       case 5:  // universite/Etudiant/_get_numCarte
       {
         int $result = (int)0;
         $result = this.numCarte ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // universite/Personne/_get_nom
       {
         String $result = null;
         $result = this.nom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // universite/Personne/_set_nom
       {
         String newNom = in.read_string ();
         this.nom (newNom);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:universite/Etudiant:1.0", 
    "IDL:universite/Personne:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Etudiant _this() 
  {
    return EtudiantHelper.narrow(
    super._this_object());
  }

  public Etudiant _this(org.omg.CORBA.ORB orb) 
  {
    return EtudiantHelper.narrow(
    super._this_object(orb));
  }


} // class EtudiantPOA
