package universite;


/**
* universite/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 3 mai 2019 10 h 05 CEST
*/

public interface Etudiant extends EtudiantOperations, universite.Personne, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
