package universite;


/**
* universite/FacHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 3 mai 2019 10 h 05 CEST
*/

abstract public class FacHelper
{
  private static String  _id = "IDL:universite/Fac:1.0";

  public static void insert (org.omg.CORBA.Any a, universite.Fac that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static universite.Fac extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (universite.FacHelper.id (), "Fac");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static universite.Fac read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FacStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, universite.Fac value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static universite.Fac narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof universite.Fac)
      return (universite.Fac)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      universite._FacStub stub = new universite._FacStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static universite.Fac unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof universite.Fac)
      return (universite.Fac)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      universite._FacStub stub = new universite._FacStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
