package universite;


/**
* universite/FacOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 3 mai 2019 10 h 05 CEST
*/

public interface FacOperations 
{
  universite.Etudiant ajouterEtudiant (String nom);
  universite.Etudiant recupererEtudiant (int numCarte);
  void retirerEtudiant (int numCarte);
  universite.Etudiant[] listerEtudiants ();
} // interface FacOperations
