package universite;


/**
* universite/PersonneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from universite.idl
* vendredi 3 mai 2019 10 h 05 CEST
*/

public interface PersonneOperations 
{
  String nom ();
  void nom (String newNom);
} // interface PersonneOperations
