package accumulator;

/**
* accumulator/AccumulatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from accumulator.idl
* vendredi 3 mai 2019 09 h 49 CEST
*/

public final class AccumulatorHolder implements org.omg.CORBA.portable.Streamable
{
  public accumulator.Accumulator value = null;

  public AccumulatorHolder ()
  {
  }

  public AccumulatorHolder (accumulator.Accumulator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = accumulator.AccumulatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    accumulator.AccumulatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return accumulator.AccumulatorHelper.type ();
  }

}
