package accumulator;


/**
* accumulator/AccumulatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from accumulator.idl
* vendredi 3 mai 2019 09 h 49 CEST
*/

abstract public class AccumulatorHelper
{
  private static String  _id = "IDL:accumulator/Accumulator:1.0";

  public static void insert (org.omg.CORBA.Any a, accumulator.Accumulator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static accumulator.Accumulator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (accumulator.AccumulatorHelper.id (), "Accumulator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static accumulator.Accumulator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AccumulatorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, accumulator.Accumulator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static accumulator.Accumulator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof accumulator.Accumulator)
      return (accumulator.Accumulator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      accumulator._AccumulatorStub stub = new accumulator._AccumulatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static accumulator.Accumulator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof accumulator.Accumulator)
      return (accumulator.Accumulator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      accumulator._AccumulatorStub stub = new accumulator._AccumulatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
