package accumulator;


/**
* accumulator/Accumulator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from accumulator.idl
* vendredi 3 mai 2019 09 h 49 CEST
*/

public interface Accumulator extends AccumulatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Accumulator
