package accumulator;


/**
* accumulator/AccumulatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from accumulator.idl
* vendredi 3 mai 2019 09 h 49 CEST
*/

public abstract class AccumulatorPOA extends org.omg.PortableServer.Servant
 implements accumulator.AccumulatorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // accumulator/Accumulator/add
       {
         int number = in.read_long ();
         this.add (number);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:accumulator/Accumulator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Accumulator _this() 
  {
    return AccumulatorHelper.narrow(
    super._this_object());
  }

  public Accumulator _this(org.omg.CORBA.ORB orb) 
  {
    return AccumulatorHelper.narrow(
    super._this_object(orb));
  }


} // class AccumulatorPOA
