package accumulator;


/**
* accumulator/AccumulatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from accumulator.idl
* vendredi 3 mai 2019 09 h 49 CEST
*/

public interface AccumulatorOperations 
{
  void add (int number);
} // interface AccumulatorOperations
