package corba;


/**
* corba/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* vendredi 3 mai 2019 14 h 30 CEST
*/

public interface ChatClientOperations 
{
  String getUserName ();
  void addMSG (String msg);
  void updateConnectedUsers (String[] names);
} // interface ChatClientOperations
