package corba;

/**
* corba/ChatClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* vendredi 3 mai 2019 14 h 30 CEST
*/

public final class ChatClientHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.ChatClient value = null;

  public ChatClientHolder ()
  {
  }

  public ChatClientHolder (corba.ChatClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.ChatClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.ChatClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.ChatClientHelper.type ();
  }

}
