package corba;


/**
* corba/NamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* vendredi 3 mai 2019 14 h 30 CEST
*/

public final class NamesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public NamesHolder ()
  {
  }

  public NamesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.NamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.NamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.NamesHelper.type ();
  }

}
